platform :ios, '12.4'
use_frameworks!

target 'FirebaseIdentity_Example' do
  pod 'FirebaseIdentity', :path => '../'
  pod 'AppController'
  pod 'Static'
  pod 'FBSDKLoginKit'

  target 'FirebaseIdentity_Tests' do
    inherit! :search_paths

  end
end
