platform :ios, '12.0'
use_frameworks!

target 'FirebaseIdentity_Example' do
  pod 'AppController'
  pod 'FBSDKLoginKit', '~> 12.0'
  pod 'FirebaseIdentity', :path => '../'
  pod 'Static'

  target 'FirebaseIdentity_Tests' do
    inherit! :search_paths

  end
end
